require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '9.0'
ENV['SWIFT_VERSION'] = '5'

target 'Serenity' do
	config = use_native_modules!
  
	use_react_native!(:path => config["reactNativePath"])
  
 pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

	target 'SerenityTests' do
	  inherit! :complete
	  # Pods for testing
	end
  
	# Enables Flipper.
	#
	# Note that if you have use_frameworks! enabled, Flipper will not work and
	# you should disable these next few lines.
	use_flipper!
	post_install do |installer|
	  flipper_post_install(installer)
	end
  end
  
  target 'Serenity-tvOS' do
	# Pods for Serenity-tvOS
  
	target 'Serenity-tvOSTests' do
	  inherit! :search_paths
	  # Pods for testing
	end
  end