#!/usr/bin/env bash
git submodule update --init
git submodule update --recursive --remote

# clean up for  now
rm -rf /node_modules
rm -rf yarn.lock

# install packages
yarn install

# make gradlew executable
chmod +x app/mobile/android/gradlew

# create android release
yarn release