#!/usr/bin/env bash
git submodule update --init --recursive

# install packages
npm install --legacy-peer-deps

# make gradlew executable
chmod +x apps/mobile/android/gradlew

# create android release
npm run release
